#spring:
#  application:
#    name: api-gateway
#
#server:
#  port: 8675
#
#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lowerCaseServiceId: true
#      routes:
##        - id: quiz-service
##          uri: lb://quiz-service
##          predicates:
##            - Path=/quiz/**
##          filters:
##            - AuthenticationFilter
#
#
##        - id: question-definition-service
##          uri: lb://question-definition-service
##          predicates:
##            - Path=/questions/**
##          filters:
##            - AuthenticationFilter
#
#        - id: USER-SERVICE
#          uri: http://localhost:8001
#          predicates:
#            - Path=/auth/**
#
##        - id: user-service
##          uri: lb://user-service/
##          predicates:
##            - Path=/user/**
##          filters:
##            - AuthenticationFilter
#
